name: 'aop-test-action'
description: 'aop-test-action'
author: 'aop-test-action author'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 1000
runs:
  using: 'node16'
  main: 'dist/index.js'
