on:
  workflow_dispatch:

jobs:
  action-packages-consume:
    runs-on: ubuntu-latest
    steps:
    - uses: aop-sanity-test/aop-test-repo@0.1.0
    - uses: aop-sanity-test/aop-test-repo@0.1.3
    - uses: aop-sanity-test/aop-test-repo@v1
    - uses: aop-sanity-test/aop-test-repo@1
    - uses: aop-sanity-test/aop-test-repo@2.0.0
